### ISSUE TITLE
Contract.Require(x != null) gets translated in "!(x &lt;= null)" in the documentation rewritten by CC

### ISSUE THREAD

**Issue by psmacchia** [Microsoft/CodeContracts#307] opened 2015-11-19 05:12 UTC
We have a lot of *require not null* contracts and I noticed that the contract formatting in the XML doc that used to be `csharp="XYZ != null"` is now `csharp="!(XYZ &lt;= null)"`. If I look in the xml generated I get:

    // XML Generated Now     csharp="!(initialSeq &lt;= null)"
    <requires description="initialSeq must not be null" csharp="!(initialSeq &lt;= null)" vb="!(initialSeq &lt;= Nothing)">!(initialSeq &lt;= null)</requires>

    // XML Generated Before  csharp="initialSeq != null"
    <requires description="initialSeq must not be null" csharp="initialSeq != null" vb="initialSeq &lt;&gt; Nothing">initialSeq != null</requires>

Here is the contract declaration in the C# code:

    // Contract declaration in the C# code
    Contract.Requires(initialSeq != null, "initialSeq must not be null");

Here is the IL emitted from VS2015 (Update 1 RC) after being rewritten with 1.9.1:

    IL_0000: ldarg.0
    IL_0001: ldnull
    IL_0002: cgt.un
    IL_0004: ldstr "initialSeq must not be null"
    IL_0009: ldstr "initialSeq != null"
    IL_000e: call void System.Diagnostics.Contracts.__ContractsRuntime::Requires(bool, string, string)
    IL_0013: nop
    IL_0014: nop
    IL_0015: br IL_001a

Here is the IL when compiled with VS2013 + Code Contract 1.7 if it can help: 

    L_0000: ldarg.0 
    L_0001: ldnull 
    L_0002: ceq 
    L_0004: ldc.i4.0 
    L_0005: ceq 
    L_0007: ldstr "initialSeq must not be null"
    L_000c: ldstr "initialSeq != null"
    L_0011: call void System.Diagnostics.Contracts.__ContractsRuntime::Requires(bool, string, string)
    L_0016: nop 
    L_0017: ldarg.1 
    L_0018: ldnull 
    L_0019: ceq 
    L_001b: ldc.i4.0 
    L_001c: ceq

This is likely cause by Roslyn - Roslyn compiler emits `x != null` as `x > null`, whereas the old <= VS2013 compiler emitted it as `(x == null) == 0` as you can see from the VS2013 IL above.

ccdocgen likely needs to be updated to understand that `x > null` also means `x != null`.

**Comment by sharwell** [comment] 2015-11-19 05:16
I find the VS2013 IL very interesting. The explicit allowing of cgt.un for null checking has been in ECMA-335 for many years. The IL does make it obvious why you are seeing what you're seeing though! :smile:

**Comment by ndykman** [comment] 2015-12-09 19:06
I created a pull request with a fix for this specific issue. It's not a more general fix, just for CCDoc. There is an existing class that tries to simplify Boolean expressions for documentation generation. I just added an additional overriding method that looks at greater than expressions, and if it sees something like x > null, it rewrites it as x != null for the documentation.

**Comment by SergeyTeplyakov** [comment] 2015-12-09 19:24
@ndykman Is it possible to add test case to cover this change?

**Comment by ndykman** [comment] 2015-12-09 21:01
Would need some guidance on where to set that up. The current regression tests for CCDoc (Microsoft.Research/RegressionTest/CCDoc) would have caught the error if the test DLL was built with VS2015 (the XML wouldn't match the expected XML doc).

**Comment by psmacchia** [comment] 2015-12-10 06:52
@ndykman when you havea fix with bits compiled, I'll be glad to test. So far this issue still force us to keep some  projects un VS2013 (those with CC, CC 1.7) and the other ones are on VS2015. Juggling with 2 IDEs is not convenient.  Thanks

**Comment by SergeyTeplyakov** [comment] 2015-12-10 07:07
@ndykman I can't remember right from my head is it possible to use the same approach that is used in Foxtrot tests: there are different cases for diferent C# compilers. If that would not be possible, I think it would be OK at least to test private bits with @psmacchia codebase to check whether the fix is good or not before accepting PR.

**Comment by psmacchia** [comment] 2015-12-10 07:46
If you have an url like  https://ci.appveyor.com/project/hubuk/codecontracts/build/1.9.11201.50/artifacts  with new bits including the fix, please let me know

**Comment by ndykman** [comment] 2015-12-11 02:21
I will look into posting the build as requested.

**Comment by ndykman** [comment] 2015-12-14 22:46
Still haven't a hard time not having AppVeyor not time out (only have the free plan). So, for now, use this link (http://1drv.ms/1lJBDpL) to get the MSI I built locally. Or, visit (http://1drv.ms/1lJBUcq) for a zipped version of the ccdocgen.exe executable only.

**Comment by psmacchia** [comment] 2015-12-18 15:40
Good news, the issue seems fixed with this last version!!  I now get again XML like

    <requires description="project must not be null" csharp="project != null" vb="project &lt;&gt; Nothing">

**Comment by taschna** [comment] 2015-12-18 17:52
@ndykman I have a problem with your MSI version:
in a fresh installed VS2015 (Community) Update 1 I get the following error from the static checker:
```
CodeContracts: BitmapHeaderLibrary: Diagnostic: Failed to connect to any cache.
(1,1): warning : CodeContracts: System.Diagnostics.Contracts.ContractDeclarativeAssemblyAttribute.#ctor()[0x6]: Cannot connect to the cache. The CodeContracts static check will not run
```

**Comment by ndykman** [comment] 2015-12-18 19:37
Oh, the build was intended to test the ccdocgen executable. It is possible that maybe something in my fork that is causing an issue, I will look into it.

**Comment by SergeyTeplyakov** [comment] 2016-01-26 01:09
Merged and should be fixed.

**Closed by SergeyTeplyakov** 2016-01-26 01:09 UTC
