### ISSUE TITLE
Version mismatch: 1.9.10714.2 Extension installer ships with vsix Manifest indicating version 1.8.10107.10 in Visual Studio 2015

### ISSUE THREAD

**Issue by DoctorVanGogh** [Microsoft/CodeContracts#332] opened 2016-01-12 10:35 UTC
If you download the current (`1.9.10714.2`) extension from https://visualstudiogallery.msdn.microsoft.com/1ec7db13-3363-46c9-851f-1ce455f66970 and install it into visual studio 2015, the extension will show as version `1.8.10107.10` in visual studio and a permanent 'Update Available' notification  will be displayed.

Checking the extensions manifest in `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\CodeContracts\1.9.10714.2` shows the following content in `extension.vsixmanifest`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<PackageManifest Version="2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011" xmlns:d="http://schemas.microsoft.com/developer/vsx-schema-design/2011">
    <Metadata>
        <Identity Version="1.8.10107.10" ...
```
A quick check with 7-zip inside the `Contracts.devlab9ts.msi` installer confirms that the file `VS14extension.manifest` is the __only__ manifest indicating a faulty version number (VS10, VS11 & VS12 manifests all show the correct 1.9.10714.2 version).

This needs an update to the installer with a correct manifest.

**Comment by hubuk** [comment] 2016-01-12 10:53
Probably duplicate of #250 and #161

**Closed** 2016-01-22 01:48 UTC
Labels: duplicate
