### ISSUE TITLE
Support for VS2015

### ISSUE THREAD

**Issue by thegreatco** [Microsoft/CodeContracts#18] opened 2015-03-07 20:13 UTC
Can we add support for VS2015? I use it for most of my projects but need to keep 2013 around for projects that use CodeContracts.

**Comment by aarondandy** [comment] 2015-03-08 00:56
I wonder if this would be a large undertaking as the compiler output from Roslyn may be different enough to cause problems. I think 2015 support is going to be very important to keep this project going but it seems like we are going to be the ones that need to do it. Hopefully somebody can get enough time to dig in and learn the code base.

**Comment by Daniel-Svensson** [comment] 2015-04-22 12:01
It seems code contracts works ok with VS 2015 but there are a few issues to fix.
This is the result om my research, hopefully if will make adding support for VS 2015 much easier.

* It does not work with code using "dynamic" since roslyn uses new metadata embedded in the pdb files.
In order to get it to work with roslyn it seems like the CCI project needs to be updated to use the latest version (if it has not already been so) .
http://dissipatedheat.com/2014/10/28/curious-case-of-code-contracts-and-roslyn/
 http://blog.xoc.net/2014/11/code-contracts-and-visual-studio-2015.html
https://roslyn.codeplex.com/workitem/54

* Target (and probably other) files installed into version specific folders need to be added at the correct corresponding locations for VS 2015
Target files which are now only copied to C:\Program Files (x86)\MSBuild\12.0\Microsoft.Common.Targets\ImportAfter\ should be copied to C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.Targets\ImportAfter\ for VS 2015
http://blog.xoc.net/2014/11/code-contracts-and-visual-studio-2015.html

* The tooling /settings tab (GUI) should be updated to work inside VS 2015

**Comment by roji** [comment] 2015-05-03 10:10
+1, thanks for doing this work!

**Comment by RxDave** [comment] 2015-05-03 13:17
+1
Looks like the CCI bug was fixed already: 
https://ccimetadata.codeplex.com/SourceControl/changeset/73073

**Comment by wasabii** [comment] 2015-05-04 16:21
Mine is actually throwing an error on 7. ;)

**Comment by Daniel-Svensson** [comment] 2015-05-08 14:57
Updated my comment above, seems like the first big issues has been fixed but immediately found a new issue,

There might be some more cases where the rewriter will miss contracts but at least it is now possible to fetch the latests source (I merged the currently pending pull requests) and get started.

**Comment by erwinwolff** [comment] 2015-05-13 12:23
Keep up the good work! I am also working with code contracts on a large project and I have to see them go.

**Comment by danielcweber** [comment] 2015-05-18 18:48
@Daniel-Svensson: Can you provide some working minimal example of some async code that makes the rewriter miss Contract.Requires when complied with Roslyn ?

**Comment by billings7** [comment] 2015-05-19 14:52
I have fixed one problem I was having (#47, pr #48), but that has lead me on to another problem that I currently have no clue how to solve (#49)

**Comment by danielcweber** [comment] 2015-05-19 19:22
I opened a separate issue for the rewriter missing Contract.Requires in async methods along with the results of some investigation.

**Comment by Daniel-Svensson** [comment] 2015-05-20 11:43
@danielcweber seems to have both reproduced and fixed the problem with async methods (tried it today). Good work! I've been waiting to get back our internet Connection at home (still some Days left :( ) so I've not had the time to add the issue myself.

**Comment by SergeyTeplyakov** [comment] 2015-07-09 21:37
All the bugs are fixed! Ready for release!

**Closed by SergeyTeplyakov** 2015-07-09 21:37 UTC
Labels: fixed

**Comment by hickford** [comment] 2015-08-20 13:22
Is it released yet?

Yes https://visualstudiogallery.msdn.microsoft.com/1ec7db13-3363-46c9-851f-1ce455f66970

**Comment by ghuntley** [comment] 2015-12-16 21:27
Thanks @SergeyTeplyakov!
