### ISSUE TITLE
1.9.10714.2 Incorrect version in extension.vsixmanifest 

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/CodeContracts#161] opened 2015-07-21 23:31 UTC
In Visual Studio 2015 a Code Contracts extension.vsixmanifest contains 1.8.10107.10 instead of 
1.9.10714.2 so Visual Studio displays a notification that update is available

**Comment by billings7** [comment] 2015-07-22 00:07
This could be due to the file [Microsoft.Research/ManagedContract.Setup/VS14.extension.vsixmanifest](https://github.com/Microsoft/CodeContracts/blob/master/Microsoft.Research/ManagedContract.Setup/VS14.extension.vsixmanifest) being picked up in the build of the setup. I assume that file was committed by mistake, as the actual vsixmanifest is in the VSIX folder.

**Comment by sharwell** [comment] 2015-07-22 05:24
Grabbed

**Comment by sharwell** [comment] 2015-07-22 05:30
@billings7 You are exactly correct regarding the cause by the way.

**Closed** 2015-07-22 05:33 UTC

**Comment by rkeithhill** [comment] 2015-09-08 04:24
Really looking forward to the update that fixes this.  Any ETA on that update?

**Comment by CreepyGnome** [comment] 2015-12-19 05:29
A workaround for people who are bothered by this and don't want to click the ignore update option in Visual Studio is to just change the file to have the correct version.

Close VS2015, Open notepad.exe as administrator, then open the impacted extension.vsixmanifest file that was installed, and change the Identity element's Version attribute to the correct version of 1.9.10714.2. Then when you reopen VS2015 the notification goes away.

**Comment by cilerler** [comment] 2016-01-25 15:32
Location of the file that @CreepyGnome mentioned above is `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\CodeContracts\1.9.10714.2`

**Comment by xperiandri** [comment] 2016-01-25 17:24
Confirm
